version: '3.3'

volumes:
  datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always

  website:
    container_name: php_site
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=helloworld
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql
